const products = [
  {
    _id: '1',
    image: '/images/d1.jpg',
    name: 'Cotton Shirt',
    brand: 'Cotton',
    category: 'Shirts',
    price: 145,
    rating: 4.5,
    reviews: 1234,
    state: 'In Stock',
    features: ['100% Cotton'],
  },
  {
    _id: '2',
    image: '/images/d2.jpg',
    name: 'Amazon Best Shirt',
    category: 'Shirts',
    brand: 'Amazon',
    price: 245,
    rating: 4.7,
    reviews: 134,
    state: 'Unavailable',
    features: [
      'Imported Machine Wash Made in Vietnam Same fit',
      'long-sleeve button-up shirt a go-to pick',
    ],
  },
  {
    _id: '3',
    image: '/images/d3.jpg',
    name: 'Amazon Fit Shirt',
    category: 'Shirts',
    brand: 'Amazon',
    price: 245,
    rating: 4.7,
    reviews: 134,
    state: 'In Stock',
    features: [
      '100% Cotton',
      'Imported Machine Wash Made in Vietnam Same fit',
      'long-sleeve button-up shirt a go-to pick',
    ],
  },
];
export default products;
